### ISSUE TITLE
Create an artifact

### ISSUE THREAD

**Issue by mohsenebrahimy** [MaryLearning/EnglishEra#6]
In order to get the result from our project add an artifact. Can you describe what is an artifact?

**Comment by MaryamEbrahimi** [comment]
in web applications, files & folders are presented in a file system as a web archive(WAR). so we ought to configure the layout of the project to be deployed to the server. In the other word,  artifact is the actual output of the project.

**Comment by MaryamEbrahimi** [comment]
but i have had problem how to add artifacts?
